trigger:
- '*'

variables:
  csproj: '**/*.csproj'

stages:
- stage: 'Build'
  displayName: 'Build Mobile Application'
  
  jobs:      
  - job: build_windows
    displayName: Build Windows Library
    pool:
    steps:
      - task: UseDotNet@2
        displayName: 'Install .NET SDK'
        inputs:
          version: '6.x'
          includePreviewVersions: true