trigger:
- '*'

variables:
  csproj: '**/*.csproj'

stages:
- stage: 'Build'
  displayName: 'Build Mobile Application'
  
  jobs:      
  - job: build_windows
    displayName: Build Windows Library
    pool:
      vmImage: 'windows-latest'
    steps:
      - task: UseDotNet@2
        displayName: 'Install .NET SDK'
        inputs:
          version: '6.x'
          includePreviewVersions: true

      - task: CmdLine@2
        displayName: 'Install .NET MAUI workload'
        inputs:
          script: |
            dotnet workload install android --ignore-failed-sources
            dotnet workload install ios --ignore-failed-sources
            dotnet workload install maccatalyst --ignore-failed-sources
            dotnet workload install maui --ignore-failed-sources