trigger:
- '*'

variables:
  csproj: '**/*.csproj'

stages:
- stage: 'Build'
  displayName: 'Build Mobile Application'
  
  jobs:      
  - job: build_ios
    displayName: Build Maui IOS
    pool:
      vmImage: 'macos-11'
    steps:
      - task: UseDotNet@2
        displayName: 'Install .NET SDK'
        inputs:
          version: '6.0.x'
          includePreviewVersions: true

      - task: PowerShell@2
        displayName: 'Install .NET MAUI workload'
        inputs:
            targetType: 'inline'
            script: | 
              dotnet workload install android --ignore-failed-sources
              dotnet workload install ios --ignore-failed-sources
              dotnet workload install maccatalyst --ignore-failed-sources
              dotnet workload install maui --ignore-failed-sources
            errorActionPreference: 'continue'

      - task: PowerShell@2
        displayName: 'Restore NuGet Packages'
        inputs:
              targetType: 'inline'
              script: 'dotnet restore src/app/SoundStreamer.Client/SoundStreamer.Client.csproj'

      - task: PowerShell@2
        displayName: Build Ios Application
        inputs:
              targetType: 'inline'
              script: 'dotnet build src/app/SoundStreamer.Client/SoundStreamer.Client.csproj -c Debug -f net6.0-ios --no-restore'